In [2]:
import os
import numpy as np
import pandas as pd
import pylab as pl
import geopandas as gpd

pd.options.display.max_columns = None
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [65]:
labels = pd.read_csv('Clean_Data/stations_class_all.csv')

In [66]:
labels.head()

,station_id,startCount_0,endCount_0,startCount_1,endCount_1,startCount_2,endCount_2,startCount_3,endCount_3,startCount_4,endCount_4,startCount_5,endCount_5,startCount_6,endCount_6,startCount_7,endCount_7,startCount_8,endCount_8,startCount_9,endCount_9,startCount_10,endCount_10,startCount_11,endCount_11,startCount_12,endCount_12,startCount_13,endCount_13,startCount_14,endCount_14,startCount_15,endCount_15,startCount_16,endCount_16,startCount_17,endCount_17,startCount_18,endCount_18,startCount_19,endCount_19,startCount_20,endCount_20,startCount_21,endCount_21,startCount_22,endCount_22,startCount_23,endCount_23,label
0,301,390.0,671.0,244.0,377.0,151.0,223.0,96.0,121.0,73.0,59.0,395.0,52.0,1462.0,178.0,2461.0,630.0,3504.0,864.0,1821.0,767.0,1685.0,1010.0,1853.0,1414.0,2189.0,1889.0,2104.0,2032.0,2059.0,2124.0,2212.0,2462.0,2219.0,2935.0,2315.0,4682.0,2420.0,4738.0,2111.0,3159.0,1479.0,2003.0,1179.0,1533.0,906.0,1317.0,620.0,907.0,1
1,445,403.0,954.0,269.0,520.0,144.0,299.0,103.0,176.0,90.0,110.0,209.0,107.0,1234.0,227.0,2888.0,618.0,7474.0,1171.0,3140.0,1072.0,2747.0,1511.0,2611.0,1803.0,2832.0,2074.0,2677.0,2394.0,2573.0,2671.0,2899.0,3023.0,2560.0,3386.0,2746.0,4882.0,2830.0,6114.0,2354.0,4526.0,1656.0,3248.0,1111.0,2408.0,807.0,1903.0,657.0,1332.0,1
2,487,172.0,534.0,113.0,306.0,51.0,212.0,60.0,131.0,192.0,68.0,619.0,65.0,2181.0,303.0,3658.0,657.0,3900.0,806.0,1390.0,664.0,1057.0,799.0,1244.0,1103.0,1546.0,1413.0,1441.0,1498.0,1502.0,1845.0,1785.0,2308.0,1769.0,2823.0,2441.0,4624.0,2119.0,4401.0,1761.0,2810.0,1242.0,2438.0,811.0,1877.0,541.0,1313.0,356.0,1006.0,1
3,504,867.0,917.0,535.0,584.0,329.0,404.0,211.0,229.0,147.0,169.0,436.0,171.0,1487.0,801.0,3578.0,1607.0,4899.0,2686.0,2616.0,1670.0,1931.0,1749.0,2305.0,2328.0,2640.0,2534.0,2629.0,2513.0,2645.0,2822.0,3043.0,3017.0,3056.0,3515.0,3977.0,5452.0,3719.0,6188.0,3240.0,4516.0,2365.0,3006.0,2067.0,2365.0,1757.0,1818.0,1432.0,1435.0,1
4,72,127.0,273.0,78.0,137.0,61.0,93.0,32.0,35.0,68.0,38.0,126.0,190.0,431.0,511.0,906.0,990.0,3545.0,1504.0,2231.0,1649.0,1618.0,1205.0,1378.0,1135.0,1384.0,1348.0,1585.0,1444.0,1735.0,1675.0,1855.0,1785.0,2034.0,1896.0,2349.0,2251.0,2306.0,2934.0,1606.0,2023.0,826.0,1738.0,589.0,1102.0,483.0,877.0,286.0,550.0,5

In [9]:
#labels = labels[[0,-1]]

In [45]:
spatial = pd.read_csv('Clean_Data/citibike_spatial_joined.csv')

In [46]:
spatial.head()

,OBJECTID,Join_Count,TARGET_FID,Join_Count_1,TARGET_FID_1,capacity,lat,lon,name,short_name,station_id,DDLat,DDLon,ORIG_OID,OBJECTID_1,Shape_Leng,zone,LocationID,borough,taxi_R_OBJECTID,taxi_R_tz,taxi_R_total,taxi_R_male,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_R_white,taxi_R_black,taxi_R_asian,taxi_R_others,taxi_R_two_or_more,taxi_R_less_high_school,taxi_R_high_school,taxi_R_college,taxi_R_bachelor,taxi_W_OBJECTID,taxi_W_tz,taxi_W_total,taxi_W_male,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over,taxi_W_white,taxi_W_black,taxi_W_asian,taxi_W_others,taxi_W_two_or_more,taxi_W_less_high_school,taxi_W_high_school,taxi_W_college,taxi_W_bachelor,nyu_2451_34513_statefp,nyu_2451_34513_countyfp,nyu_2451_34513_tractce,nyu_2451_34513_geoid,nyu_2451_34513_name,nyu_2451_34513_namelsad,nyu_2451_34513_mtfcc,nyu_2451_34513_funcstat,nyu_2451_34513_aland,nyu_2451_34513_awater,nyu_2451_34513_intptlat,nyu_2451_34513_intptlon,nyu_2451_34513_ct,census_csv_CensusTract,census_csv_County,census_csv_Borough,census_csv_Income,census_csv_IncomePerCap,census_csv_Drive,census_csv_Carpool,census_csv_Transit,census_csv_Walk,census_csv_OtherTransp,census_csv_WorkAtHome,census_csv_MeanCommute,census_csv_Employed,census_csv_PrivateWork,census_csv_PublicWork,census_csv_SelfEmployed,census_csv_FamilyWork,census_csv_Unemployment
0,1,1,1,1,1,37,40.722174,-73.983688,E 2 St & Avenue B,5515.02,301,40.72218270N,073.98368923W,1,79,0.042625,East Village,79,Manhattan,78,79,23766,0.503408,0.335984,0.501262,0.162754,0.792561,0.065472,0.116216,0.005975,0.019776,0.069259,0.120929,0.176513,0.297315,76,79,26074,0.469510,0.251400,0.544182,0.204418,0.612411,0.218225,0.142901,0.008438,0.018026,0.100445,0.157437,0.225090,0.265629,36,61,3002,36061003002,30.02,Census Tract 30.02,G5020,S,78525,0,40.722964,-73.985866,3.606100e+10,3.606100e+10,New York,Manhattan,50625.0,46124.0,4.5,0.3,59.5,22.2,10.3,3.1,29.6,0.687036,82.6,8.0,8.9,0.5,3.9
1,2,1,2,1,2,52,40.727408,-73.981420,E 10 St & Avenue A,5659.05,445,40.72741620N,073.98142150W,2,79,0.042625,East Village,79,Manhattan,78,79,23766,0.503408,0.335984,0.501262,0.162754,0.792561,0.065472,0.116216,0.005975,0.019776,0.069259,0.120929,0.176513,0.297315,76,79,26074,0.469510,0.251400,0.544182,0.204418,0.612411,0.218225,0.142901,0.008438,0.018026,0.100445,0.157437,0.225090,0.265629,36,61,3200,36061003200,32.00,Census Tract 32,G5020,S,217682,0,40.725558,-73.983717,3.606100e+10,3.606100e+10,New York,Manhattan,71033.0,58068.0,1.0,0.0,59.7,20.4,12.2,6.7,30.8,0.631432,83.2,6.0,10.8,0.0,4.4
2,3,1,3,1,3,34,40.733143,-73.975739,E 20 St & FDR Drive,5886.02,487,40.73315085N,073.97574025W,3,224,0.044020,Stuy Town/Peter Cooper Village,224,Manhattan,222,224,10453,0.471922,0.310246,0.479193,0.210562,0.800057,0.059600,0.114417,0.003731,0.022195,0.054912,0.111164,0.176217,0.347460,218,224,1407,0.611940,0.199716,0.538735,0.261549,0.668088,0.209666,0.095238,0.009950,0.017058,0.169865,0.178394,0.233120,0.218905,36,61,4400,36061004400,44.00,Census Tract 44,G5020,S,410435,464126,40.728096,-73.971452,3.606100e+10,3.606100e+10,New York,Manhattan,93010.0,57640.0,3.7,3.8,58.1,20.3,4.8,9.2,29.7,0.626420,77.7,13.4,8.9,0.0,2.6
3,4,1,4,1,4,44,40.732219,-73.981656,1 Ave & E 16 St,5779.08,504,40.73222679N,073.98165701W,4,224,0.044020,Stuy Town/Peter Cooper Village,224,Manhattan,222,224,10453,0.471922,0.310246,0.479193,0.210562,0.800057,0.059600,0.114417,0.003731,0.022195,0.054912,0.111164,0.176217,0.347460,218,224,1407,0.611940,0.199716,0.538735,0.261549,0.668088,0.209666,0.095238,0.009950,0.017058,0.169865,0.178394,0.233120,0.218905,36,61,4400,36061004400,44.00,Census Tract 44,G5020,S,410435,464126,40.728096,-73.971452,3.606100e+10,3.606100e+10,New York,Manhattan,93010.0,57640.0,3.7,3.8,58.1,20.3,4.8,9.2,29.7,0.626420,77.7,13.4,8.9,0.0,2.6
4,5,1,5,1,5,39,40.767272,-73.993929,W 52 St & 11 Ave,6926.01,72,40.76728043N,073.99393033W,5,50,0.055748,Clinton West,50,Manhattan,49,50,8282,0.556991,0.251509,0.597923,0.150567,0.713354,0.116276,0.144047,0.007969,0.018353,0.077035,0.131490,0.197175,0.342792,48,50,25889,0.614392,0.225115,0.608173,0.166712,0.681679,0.195179,0.100042,0.007185,0.015914,0.078952,0.141064,0.203059,0.351810,36,61,13500,36061013500,135.00,Census Tract 135,G5020,S,420500,411667,40.770263,-73.995972,3.606101e+10,3.606101e+10,New York,Manhattan,62290.0,65809.0,6.9,1.1,41.0,39.5,7.9,3.7,28.0,0.538534,84.9,7.2,7.9,0.0,5.7

In [47]:
spatial = spatial[['station_id', 'taxi_R_tz', 'taxi_R_total', 'taxi_R_male', 'taxi_R_age_under_29', 'taxi_R_age_30_54', 'taxi_R_age_55_over',
        'taxi_W_total', 'taxi_W_male', 'taxi_W_age_under_29', 'taxi_W_age_30_54', 'taxi_W_age_55_over']]

In [48]:
spatial.head()

,station_id,taxi_R_tz,taxi_R_total,taxi_R_male,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_W_total,taxi_W_male,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over
0,301,79,23766,0.503408,0.335984,0.501262,0.162754,26074,0.469510,0.251400,0.544182,0.204418
1,445,79,23766,0.503408,0.335984,0.501262,0.162754,26074,0.469510,0.251400,0.544182,0.204418
2,487,224,10453,0.471922,0.310246,0.479193,0.210562,1407,0.611940,0.199716,0.538735,0.261549
3,504,224,10453,0.471922,0.310246,0.479193,0.210562,1407,0.611940,0.199716,0.538735,0.261549
4,72,50,8282,0.556991,0.251509,0.597923,0.150567,25889,0.614392,0.225115,0.608173,0.166712

In [49]:
spatial = spatial.rename(columns={'taxi_R_tz': "taxi_zone"})

In [50]:
spatial.shape

(768, 12)

In [53]:
#spatial[list(range(8,12))]

#for i in range(3,7):
    #spatial[[i]] = spatial[[i]]*spatial[[2]]
spatial[['taxi_R_male','taxi_R_age_under_29','taxi_R_age_30_54','taxi_R_age_55_over']] = spatial.apply(lambda x: x[3:7]*x[2], axis=1)
spatial[['taxi_W_male','taxi_W_age_under_29','taxi_W_age_30_54','taxi_W_age_55_over']] = spatial.apply(lambda x: x[8:12]*x[7], axis=1)

In [54]:
spatial.head()

,station_id,taxi_zone,taxi_R_total,taxi_R_male,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_W_total,taxi_W_male,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over
0,301,79,23766,11964.0,7985.0,11913.0,3868.0,26074,12242.0,6555.0,14189.0,5330.0
1,445,79,23766,11964.0,7985.0,11913.0,3868.0,26074,12242.0,6555.0,14189.0,5330.0
2,487,224,10453,4933.0,3243.0,5009.0,2201.0,1407,861.0,281.0,758.0,368.0
3,504,224,10453,4933.0,3243.0,5009.0,2201.0,1407,861.0,281.0,758.0,368.0
4,72,50,8282,4613.0,2083.0,4952.0,1247.0,25889,15906.0,5828.0,15745.0,4316.0

In [55]:
spatial['taxi_R_female'] = spatial['taxi_R_total'] - spatial['taxi_R_male']
spatial['taxi_W_female'] = spatial['taxi_W_total'] - spatial['taxi_W_male']

In [57]:
spatial.head()

,station_id,taxi_zone,taxi_R_total,taxi_R_male,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_W_total,taxi_W_male,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over,taxi_R_female,taxi_W_female
0,301,79,23766,11964.0,7985.0,11913.0,3868.0,26074,12242.0,6555.0,14189.0,5330.0,11802.0,13832.0
1,445,79,23766,11964.0,7985.0,11913.0,3868.0,26074,12242.0,6555.0,14189.0,5330.0,11802.0,13832.0
2,487,224,10453,4933.0,3243.0,5009.0,2201.0,1407,861.0,281.0,758.0,368.0,5520.0,546.0
3,504,224,10453,4933.0,3243.0,5009.0,2201.0,1407,861.0,281.0,758.0,368.0,5520.0,546.0
4,72,50,8282,4613.0,2083.0,4952.0,1247.0,25889,15906.0,5828.0,15745.0,4316.0,3669.0,9983.0

In [62]:
cols = list(spatial)
# move the column to head of list using index, pop and insert
cols.insert(4, cols.pop(cols.index('taxi_R_female')))
cols.insert(10, cols.pop(cols.index('taxi_W_female')))
cols

['station_id',
 'taxi_zone',
 'taxi_R_total',
 'taxi_R_male',
 'taxi_R_female',
 'taxi_R_age_under_29',
 'taxi_R_age_30_54',
 'taxi_R_age_55_over',
 'taxi_W_total',
 'taxi_W_male',
 'taxi_W_female',
 'taxi_W_age_under_29',
 'taxi_W_age_30_54',
 'taxi_W_age_55_over']

In [63]:
spatial = spatial.ix[:, cols]

In [64]:
spatial.head()

,station_id,taxi_zone,taxi_R_total,taxi_R_male,taxi_R_female,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_W_total,taxi_W_male,taxi_W_female,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over
0,301,79,23766,11964.0,11802.0,7985.0,11913.0,3868.0,26074,12242.0,13832.0,6555.0,14189.0,5330.0
1,445,79,23766,11964.0,11802.0,7985.0,11913.0,3868.0,26074,12242.0,13832.0,6555.0,14189.0,5330.0
2,487,224,10453,4933.0,5520.0,3243.0,5009.0,2201.0,1407,861.0,546.0,281.0,758.0,368.0
3,504,224,10453,4933.0,5520.0,3243.0,5009.0,2201.0,1407,861.0,546.0,281.0,758.0,368.0
4,72,50,8282,4613.0,3669.0,2083.0,4952.0,1247.0,25889,15906.0,9983.0,5828.0,15745.0,4316.0

In [12]:
# work/reside, female/male, old/yound, subway station

In [68]:
spatial = spatial.merge(labels)

In [82]:
spatial.head()

,station_id,taxi_zone,taxi_R_total,taxi_R_male,taxi_R_female,taxi_R_age_under_29,taxi_R_age_30_54,taxi_R_age_55_over,taxi_W_total,taxi_W_male,taxi_W_female,taxi_W_age_under_29,taxi_W_age_30_54,taxi_W_age_55_over,startCount_0,endCount_0,startCount_1,endCount_1,startCount_2,endCount_2,startCount_3,endCount_3,startCount_4,endCount_4,startCount_5,endCount_5,startCount_6,endCount_6,startCount_7,endCount_7,startCount_8,endCount_8,startCount_9,endCount_9,startCount_10,endCount_10,startCount_11,endCount_11,startCount_12,endCount_12,startCount_13,endCount_13,startCount_14,endCount_14,startCount_15,endCount_15,startCount_16,endCount_16,startCount_17,endCount_17,startCount_18,endCount_18,startCount_19,endCount_19,startCount_20,endCount_20,startCount_21,endCount_21,startCount_22,endCount_22,startCount_23,endCount_23,label
0,301,79,23766,11964.0,11802.0,7985.0,11913.0,3868.0,26074,12242.0,13832.0,6555.0,14189.0,5330.0,390.0,671.0,244.0,377.0,151.0,223.0,96.0,121.0,73.0,59.0,395.0,52.0,1462.0,178.0,2461.0,630.0,3504.0,864.0,1821.0,767.0,1685.0,1010.0,1853.0,1414.0,2189.0,1889.0,2104.0,2032.0,2059.0,2124.0,2212.0,2462.0,2219.0,2935.0,2315.0,4682.0,2420.0,4738.0,2111.0,3159.0,1479.0,2003.0,1179.0,1533.0,906.0,1317.0,620.0,907.0,1
1,445,79,23766,11964.0,11802.0,7985.0,11913.0,3868.0,26074,12242.0,13832.0,6555.0,14189.0,5330.0,403.0,954.0,269.0,520.0,144.0,299.0,103.0,176.0,90.0,110.0,209.0,107.0,1234.0,227.0,2888.0,618.0,7474.0,1171.0,3140.0,1072.0,2747.0,1511.0,2611.0,1803.0,2832.0,2074.0,2677.0,2394.0,2573.0,2671.0,2899.0,3023.0,2560.0,3386.0,2746.0,4882.0,2830.0,6114.0,2354.0,4526.0,1656.0,3248.0,1111.0,2408.0,807.0,1903.0,657.0,1332.0,1
2,487,224,10453,4933.0,5520.0,3243.0,5009.0,2201.0,1407,861.0,546.0,281.0,758.0,368.0,172.0,534.0,113.0,306.0,51.0,212.0,60.0,131.0,192.0,68.0,619.0,65.0,2181.0,303.0,3658.0,657.0,3900.0,806.0,1390.0,664.0,1057.0,799.0,1244.0,1103.0,1546.0,1413.0,1441.0,1498.0,1502.0,1845.0,1785.0,2308.0,1769.0,2823.0,2441.0,4624.0,2119.0,4401.0,1761.0,2810.0,1242.0,2438.0,811.0,1877.0,541.0,1313.0,356.0,1006.0,1
3,504,224,10453,4933.0,5520.0,3243.0,5009.0,2201.0,1407,861.0,546.0,281.0,758.0,368.0,867.0,917.0,535.0,584.0,329.0,404.0,211.0,229.0,147.0,169.0,436.0,171.0,1487.0,801.0,3578.0,1607.0,4899.0,2686.0,2616.0,1670.0,1931.0,1749.0,2305.0,2328.0,2640.0,2534.0,2629.0,2513.0,2645.0,2822.0,3043.0,3017.0,3056.0,3515.0,3977.0,5452.0,3719.0,6188.0,3240.0,4516.0,2365.0,3006.0,2067.0,2365.0,1757.0,1818.0,1432.0,1435.0,1
4,72,50,8282,4613.0,3669.0,2083.0,4952.0,1247.0,25889,15906.0,9983.0,5828.0,15745.0,4316.0,127.0,273.0,78.0,137.0,61.0,93.0,32.0,35.0,68.0,38.0,126.0,190.0,431.0,511.0,906.0,990.0,3545.0,1504.0,2231.0,1649.0,1618.0,1205.0,1378.0,1135.0,1384.0,1348.0,1585.0,1444.0,1735.0,1675.0,1855.0,1785.0,2034.0,1896.0,2349.0,2251.0,2306.0,2934.0,1606.0,2023.0,826.0,1738.0,589.0,1102.0,483.0,877.0,286.0,550.0,5

In [86]:
spatial.columns

Index(['station_id', 'taxi_zone', 'taxi_R_total', 'taxi_R_male',
       'taxi_R_female', 'taxi_R_age_under_29', 'taxi_R_age_30_54',
       'taxi_R_age_55_over', 'taxi_W_total', 'taxi_W_male', 'taxi_W_female',
       'taxi_W_age_under_29', 'taxi_W_age_30_54', 'taxi_W_age_55_over',
       'startCount_0', 'endCount_0', 'startCount_1', 'endCount_1',
       'startCount_2', 'endCount_2', 'startCount_3', 'endCount_3',
       'startCount_4', 'endCount_4', 'startCount_5', 'endCount_5',
       'startCount_6', 'endCount_6', 'startCount_7', 'endCount_7',
       'startCount_8', 'endCount_8', 'startCount_9', 'endCount_9',
       'startCount_10', 'endCount_10', 'startCount_11', 'endCount_11',
       'startCount_12', 'endCount_12', 'startCount_13', 'endCount_13',
       'startCount_14', 'endCount_14', 'startCount_15', 'endCount_15',
       'startCount_16', 'endCount_16', 'startCount_17', 'endCount_17',
       'startCount_18', 'endCount_18', 'startCount_19', 'endCount_19',
       'startCount_20', 'endCount_20', 'startCount_21', 'endCount_21',
       'startCount_22', 'endCount_22', 'startCount_23', 'endCount_23',
       'label'],
      dtype='object')

In [78]:
# work/reside, female/male, old/yound,

#spatial_labels = [spatial[spatial['label']==i] for i in range(0,6)]

In [79]:
#spatial_labels[0]

In [80]:
#startCount_8

In [84]:
# 8am start
y = spatial['startCount_8']
X = spatial[['taxi_R_total', 'taxi_R_male', 'taxi_R_female', 'taxi_R_age_under_29', 'taxi_R_age_30_54', 'taxi_R_age_55_over',
        'taxi_W_total', 'taxi_W_male', 'taxi_W_female', 'taxi_W_age_under_29', 'taxi_W_age_30_54', 'taxi_W_age_55_over']]

In [89]:
def NZPopCorr(col1,col2):
    ind=(spatial[col1]>0)&(spatial[col2]>0)
    return np.corrcoef(spatial[col1][ind],spatial[col2][ind])[0][1]

In [92]:
census = ['taxi_R_total', 'taxi_R_male', 'taxi_R_female', 'taxi_R_age_under_29', 'taxi_R_age_30_54',
          'taxi_R_age_55_over', 'taxi_W_total', 'taxi_W_male', 'taxi_W_female', 'taxi_W_age_under_29', 
          'taxi_W_age_30_54', 'taxi_W_age_55_over',]
start = ['startCount_0',  'startCount_1', 'startCount_2',  'startCount_3', 'startCount_4',  'startCount_5', 
         'startCount_6', 'startCount_7', 'startCount_8', 'startCount_9', 'startCount_10', 'startCount_11', 
         'startCount_12', 'startCount_13', 'startCount_14',  'startCount_15', 'startCount_16', 'startCount_17', 
         'startCount_18', 'startCount_19', 'startCount_20', 'startCount_21', 'startCount_22', 'startCount_23', ]
end = ['endCount_0', 'endCount_1', 'endCount_2', 'endCount_3', 'endCount_4', 'endCount_5', 
       'endCount_6', 'endCount_7', 'endCount_8', 'endCount_9', 'endCount_10', 'endCount_11', 
       'endCount_12', 'endCount_13', 'endCount_14', 'endCount_15', 'endCount_16', 'endCount_17', 
       'endCount_18', 'endCount_19', 'endCount_20', 'endCount_21', 'endCount_22', 'endCount_23']
print('\tCensus | {}\t | {}\t | {}\t |'.format(census[0],census[1],census[2],census[3],census[4],census[5],
                                                 census[6],census[7],census[8],census[9],census[10],census[11]))
for A in start:
    C=[]
    for P in census:
        C+=[NZPopCorr(A,P)]   
    print('%16s | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t | %.2f\t |'% (A,C[0],C[1],C[2],C[3],C[4],C[5],C[6],C[7],C[8],C[9],C[10],C[11]))    
    print(A, C)

	Census | taxi_R_total	 | taxi_R_male	 | taxi_R_female	 |
    startCount_0 | -0.16	 | -0.13	 | -0.18	 | -0.09	 | -0.20	 | -0.11	 | 0.09	 | 0.08	 | 0.10	 | 0.16	 | 0.08	 | 0.05	 |
startCount_0 [-0.15597818706275385, -0.12536898621643508, -0.1823945211713621, -0.088505405091441988, -0.19791241215668201, -0.10745441756830146, 0.089974809961257854, 0.083043860230263764, 0.095614242614515024, 0.15962279737960425, 0.077133811509624881, 0.047519270960084271]
    startCount_1 | -0.14	 | -0.12	 | -0.17	 | -0.07	 | -0.19	 | -0.11	 | 0.09	 | 0.08	 | 0.09	 | 0.16	 | 0.07	 | 0.05	 |
startCount_1 [-0.14393402828528992, -0.11531556360309494, -0.16862773795045188, -0.069599137741648331, -0.18655198676700604, -0.10706507671617595, 0.085862125564246786, 0.078527857081794786, 0.09199422888432808, 0.15538631978933548, 0.072348661988220403, 0.045771516003068495]
    startCount_2 | -0.12	 | -0.09	 | -0.14	 | -0.04	 | -0.16	 | -0.08	 | 0.06	 | 0.05	 | 0.07	 | 0.12	 | 0.05	 | 0.02	 |
startCount_2 [-0.11637202494844513, -0.089387347939753309, -0.13992399615628542, -0.044143262608891856, -0.15983085300760985, -0.078203915234832971, 0.058391791578726253, 0.050997901465073305, 0.065062453860584776, 0.11775273392812932, 0.046868718565871492, 0.02499459671972732]
    startCount_3 | -0.11	 | -0.08	 | -0.13	 | -0.03	 | -0.15	 | -0.07	 | 0.01	 | 0.01	 | 0.01	 | 0.06	 | 0.00	 | -0.02	 |
startCount_3 [-0.10707295316282095, -0.083713028235415446, -0.12737077863126683, -0.031314681126766539, -0.15129352796915926, -0.074668562773549607, 0.011849863438738164, 0.0097242627664688788, 0.013858651694583841, 0.062423743182234183, 0.0029860409197364447, -0.017197814106571754]
    startCount_4 | -0.11	 | -0.09	 | -0.13	 | -0.04	 | -0.16	 | -0.05	 | 0.04	 | 0.04	 | 0.04	 | 0.08	 | 0.03	 | 0.01	 |
startCount_4 [-0.10972871615274256, -0.087618737362555751, -0.12901739625943706, -0.041457176285381696, -0.15666959701056751, -0.054126378824409835, 0.038725416218948823, 0.040348373589701961, 0.036337454680744556, 0.078769442434728734, 0.031650694252899646, 0.014257232878279723]
    startCount_5 | -0.11	 | -0.10	 | -0.13	 | -0.08	 | -0.14	 | -0.06	 | 0.13	 | 0.12	 | 0.13	 | 0.16	 | 0.12	 | 0.11	 |
startCount_5 [-0.11407725118427042, -0.099137938499097022, -0.126532774000119, -0.083967055734851942, -0.13892442490008436, -0.064288126730599027, 0.12585100402414831, 0.12212616715893164, 0.12749689976976067, 0.16457870840327346, 0.11535900015900491, 0.10775773055524979]
    startCount_6 | -0.10	 | -0.07	 | -0.12	 | -0.07	 | -0.13	 | -0.03	 | 0.15	 | 0.14	 | 0.15	 | 0.19	 | 0.14	 | 0.12	 |
startCount_6 [-0.098632460703518901, -0.074945471209075673, -0.11929588453661917, -0.074514941624472239, -0.12693481577569993, -0.030813070582169724, 0.14754451111580777, 0.14476208946378205, 0.14781330066348403, 0.19091813036441191, 0.13895648492956142, 0.11753113307745197]
    startCount_7 | -0.13	 | -0.10	 | -0.15	 | -0.09	 | -0.17	 | -0.04	 | 0.16	 | 0.16	 | 0.16	 | 0.21	 | 0.15	 | 0.12	 |
startCount_7 [-0.12957230307784595, -0.10366070754900297, -0.1519512948745517, -0.089441987686198834, -0.17251107793671175, -0.036428638774246416, 0.16160077359669386, 0.16016239025404841, 0.16022626143733612, 0.21374772525952776, 0.15446989021234903, 0.11699562624626682]
    startCount_8 | -0.19	 | -0.17	 | -0.21	 | -0.14	 | -0.24	 | -0.10	 | 0.19	 | 0.18	 | 0.19	 | 0.25	 | 0.18	 | 0.14	 |
startCount_8 [-0.19062165887158286, -0.1709446969061022, -0.20679571097243613, -0.13564753813255431, -0.23601487205576427, -0.10356001638745232, 0.18875427622504079, 0.18328808507956046, 0.1911072667985278, 0.2472875833961721, 0.17966381590861372, 0.14149267905180812]
    startCount_9 | -0.28	 | -0.26	 | -0.30	 | -0.23	 | -0.32	 | -0.20	 | 0.29	 | 0.28	 | 0.30	 | 0.37	 | 0.28	 | 0.23	 |
startCount_9 [-0.280853949771809, -0.26050318631874575, -0.29683262903455188, -0.2264992052111397, -0.31784676731227252, -0.2029430106982324, 0.29057303663545014, 0.28085364814371738, 0.29555880862898554, 0.36984924620400395, 0.27532465212464646, 0.2332561788125444]
   startCount_10 | -0.30	 | -0.27	 | -0.32	 | -0.24	 | -0.33	 | -0.21	 | 0.28	 | 0.27	 | 0.28	 | 0.36	 | 0.26	 | 0.21	 |
startCount_10 [-0.29735912775203993, -0.27243923072303167, -0.31734478284432382, -0.24442805438601939, -0.33402843707631574, -0.21497443587226409, 0.27645083644490043, 0.26828091479535271, 0.28007491638301785, 0.35908654935840967, 0.26278504351066195, 0.21163057899385521]
   startCount_11 | -0.34	 | -0.32	 | -0.36	 | -0.29	 | -0.37	 | -0.26	 | 0.30	 | 0.29	 | 0.30	 | 0.38	 | 0.29	 | 0.23	 |
startCount_11 [-0.34007949869235865, -0.31668649050620445, -0.35829184448125112, -0.28720224882227247, -0.37404730514394741, -0.25816716556973246, 0.29772434149199434, 0.29165647360556463, 0.29877355758672747, 0.37822803649770093, 0.28546632458721299, 0.2298055486055614]
   startCount_12 | -0.37	 | -0.35	 | -0.39	 | -0.31	 | -0.40	 | -0.30	 | 0.34	 | 0.33	 | 0.33	 | 0.42	 | 0.32	 | 0.26	 |
startCount_12 [-0.37195879471784393, -0.34892711623147271, -0.38958677479226195, -0.31477591515273368, -0.40492501688446991, -0.29502630608175451, 0.33548221580873194, 0.33030406460840622, 0.33493277305029273, 0.41629795824504506, 0.32345428528992748, 0.26437494638150194]
   startCount_13 | -0.38	 | -0.35	 | -0.39	 | -0.32	 | -0.41	 | -0.30	 | 0.33	 | 0.32	 | 0.33	 | 0.41	 | 0.32	 | 0.26	 |
startCount_13 [-0.37544452450781785, -0.35193513012212158, -0.39347580872291044, -0.32098163774259736, -0.40701185595604633, -0.29772418022449498, 0.3279492930507753, 0.32368165841379404, 0.32658190182143554, 0.41080384221904814, 0.31559307354075233, 0.25604602734084864]
   startCount_14 | -0.38	 | -0.36	 | -0.40	 | -0.33	 | -0.41	 | -0.31	 | 0.31	 | 0.31	 | 0.31	 | 0.40	 | 0.30	 | 0.24	 |
startCount_14 [-0.38387806048046219, -0.36045822805904815, -0.40175726586328431, -0.33368965422109392, -0.412887798234856, -0.30583651305899917, 0.31427642579815401, 0.31018041640989358, 0.31296716901236216, 0.39633539384730981, 0.30271567200338256, 0.24162329838991517]
   startCount_15 | -0.39	 | -0.37	 | -0.41	 | -0.34	 | -0.42	 | -0.31	 | 0.32	 | 0.32	 | 0.32	 | 0.40	 | 0.31	 | 0.25	 |
startCount_15 [-0.39094539228133873, -0.36866529605680698, -0.4077254225078521, -0.3357466408230726, -0.42151483447512655, -0.31492912254297989, 0.3188504434583076, 0.31621847805571435, 0.31592894105378916, 0.39867369349602721, 0.30802855103750776, 0.24616304288642546]
   startCount_16 | -0.42	 | -0.40	 | -0.44	 | -0.36	 | -0.45	 | -0.35	 | 0.43	 | 0.43	 | 0.42	 | 0.50	 | 0.42	 | 0.35	 |
startCount_16 [-0.42269090851263386, -0.40246680887929215, -0.43728194926177832, -0.35935428114830253, -0.45371503591571416, -0.35271753112222665, 0.42741589009516551, 0.42811744726429235, 0.41907543024596233, 0.50493986418147419, 0.4177426632332995, 0.34751029185180649]
   startCount_17 | -0.42	 | -0.41	 | -0.44	 | -0.36	 | -0.45	 | -0.37	 | 0.50	 | 0.49	 | 0.49	 | 0.57	 | 0.48	 | 0.42	 |
startCount_17 [-0.42400011947295002, -0.40631514317040524, -0.4363077264991283, -0.35806731053554675, -0.45227446463888915, -0.36751258925141844, 0.4953033962145631, 0.49384521602181725, 0.48801535341978391, 0.56881880937605911, 0.48480526288711551, 0.41827758239889418]
   startCount_18 | -0.36	 | -0.34	 | -0.38	 | -0.31	 | -0.39	 | -0.30	 | 0.37	 | 0.36	 | 0.37	 | 0.45	 | 0.36	 | 0.30	 |
startCount_18 [-0.36069939453619498, -0.33936176555713637, -0.37686099372311532, -0.3054161927858004, -0.38797269679037871, -0.30052818744599669, 0.36858176877661081, 0.36193501229046848, 0.36896952493179291, 0.44511966168132294, 0.35511234522253843, 0.30441681108433016]
   startCount_19 | -0.32	 | -0.29	 | -0.34	 | -0.27	 | -0.35	 | -0.25	 | 0.26	 | 0.26	 | 0.27	 | 0.34	 | 0.25	 | 0.20	 |
startCount_19 [-0.31933913675825326, -0.29422414249447532, -0.33928071763401668, -0.26641305781535907, -0.34937013752957463, -0.25390638952459182, 0.26395802206896524, 0.25658875164003331, 0.26695396834981611, 0.34296360954938143, 0.25021443289135126, 0.20396531286399705]
   startCount_20 | -0.28	 | -0.26	 | -0.30	 | -0.23	 | -0.31	 | -0.22	 | 0.20	 | 0.19	 | 0.20	 | 0.28	 | 0.19	 | 0.14	 |
startCount_20 [-0.28276117684668878, -0.25715281051159372, -0.30350417401829688, -0.23093128560928444, -0.31460037592241941, -0.21677589135583178, 0.19908745566381314, 0.1930537065170011, 0.20184608501166806, 0.27524753269154351, 0.1861581190643809, 0.14352812828087788]
   startCount_21 | -0.24	 | -0.21	 | -0.26	 | -0.19	 | -0.27	 | -0.17	 | 0.16	 | 0.16	 | 0.17	 | 0.24	 | 0.15	 | 0.11	 |
startCount_21 [-0.23767696823301987, -0.20810812036820522, -0.26244978508165884, -0.18764686837035971, -0.27248292844355698, -0.16730185155230556, 0.16195856271770087, 0.15584304007962116, 0.1654650053430978, 0.23648658919037158, 0.1487028441238529, 0.11128805896037007]
   startCount_22 | -0.19	 | -0.16	 | -0.22	 | -0.14	 | -0.23	 | -0.12	 | 0.14	 | 0.13	 | 0.14	 | 0.21	 | 0.12	 | 0.09	 |
startCount_22 [-0.19317044386919141, -0.16037003092294991, -0.22124984673186954, -0.13978096965386655, -0.23168721491127744, -0.12468792897615635, 0.13567345075214576, 0.13029437371300934, 0.13887700664505953, 0.20755689038042902, 0.12264379845334625, 0.088709175136180457]

   startCount_23 | -0.18	 | -0.15	 | -0.20	 | -0.12	 | -0.22	 | -0.12	 | 0.12	 | 0.11	 | 0.12	 | 0.19	 | 0.10	 | 0.07	 |
startCount_23 [-0.17755974594333618, -0.14648712650246348, -0.20420754143440675, -0.11780102424821177, -0.21789674160555575, -0.1170476548689721, 0.11541607116260905, 0.10773865623180701, 0.12138209908665698, 0.18574784913201889, 0.10226197943990736, 0.071674691294496093]

In [106]:
print(' Census | {} | {} | {} | {} | {} | {} |'.format(census[0],census[1],census[2],census[3],census[4],census[5]))
for A in start:
    C=[]
    for P in census:
        C+=[NZPopCorr(A,P)]   
    print('%8s| %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t |'% (A,C[0],C[1],C[2],C[3],C[4],C[5]))    
    #print(A, C)

 Census | taxi_R_total | taxi_R_male | taxi_R_female | taxi_R_age_under_29 | taxi_R_age_30_54 | taxi_R_age_55_over |
startCount_0| -0.1560	 | -0.1254	 | -0.1824	 | -0.0885	 | -0.1979	 | -0.1075	 |
startCount_1| -0.1439	 | -0.1153	 | -0.1686	 | -0.0696	 | -0.1866	 | -0.1071	 |
startCount_2| -0.1164	 | -0.0894	 | -0.1399	 | -0.0441	 | -0.1598	 | -0.0782	 |
startCount_3| -0.1071	 | -0.0837	 | -0.1274	 | -0.0313	 | -0.1513	 | -0.0747	 |
startCount_4| -0.1097	 | -0.0876	 | -0.1290	 | -0.0415	 | -0.1567	 | -0.0541	 |
startCount_5| -0.1141	 | -0.0991	 | -0.1265	 | -0.0840	 | -0.1389	 | -0.0643	 |
startCount_6| -0.0986	 | -0.0749	 | -0.1193	 | -0.0745	 | -0.1269	 | -0.0308	 |
startCount_7| -0.1296	 | -0.1037	 | -0.1520	 | -0.0894	 | -0.1725	 | -0.0364	 |
startCount_8| -0.1906	 | -0.1709	 | -0.2068	 | -0.1356	 | -0.2360	 | -0.1036	 |
startCount_9| -0.2809	 | -0.2605	 | -0.2968	 | -0.2265	 | -0.3178	 | -0.2029	 |
startCount_10| -0.2974	 | -0.2724	 | -0.3173	 | -0.2444	 | -0.3340	 | -0.2150	 |
startCount_11| -0.3401	 | -0.3167	 | -0.3583	 | -0.2872	 | -0.3740	 | -0.2582	 |
startCount_12| -0.3720	 | -0.3489	 | -0.3896	 | -0.3148	 | -0.4049	 | -0.2950	 |
startCount_13| -0.3754	 | -0.3519	 | -0.3935	 | -0.3210	 | -0.4070	 | -0.2977	 |
startCount_14| -0.3839	 | -0.3605	 | -0.4018	 | -0.3337	 | -0.4129	 | -0.3058	 |
startCount_15| -0.3909	 | -0.3687	 | -0.4077	 | -0.3357	 | -0.4215	 | -0.3149	 |
startCount_16| -0.4227	 | -0.4025	 | -0.4373	 | -0.3594	 | -0.4537	 | -0.3527	 |
startCount_17| -0.4240	 | -0.4063	 | -0.4363	 | -0.3581	 | -0.4523	 | -0.3675	 |
startCount_18| -0.3607	 | -0.3394	 | -0.3769	 | -0.3054	 | -0.3880	 | -0.3005	 |
startCount_19| -0.3193	 | -0.2942	 | -0.3393	 | -0.2664	 | -0.3494	 | -0.2539	 |
startCount_20| -0.2828	 | -0.2572	 | -0.3035	 | -0.2309	 | -0.3146	 | -0.2168	 |
startCount_21| -0.2377	 | -0.2081	 | -0.2624	 | -0.1876	 | -0.2725	 | -0.1673	 |
startCount_22| -0.1932	 | -0.1604	 | -0.2212	 | -0.1398	 | -0.2317	 | -0.1247	 |
startCount_23| -0.1776	 | -0.1465	 | -0.2042	 | -0.1178	 | -0.2179	 | -0.1170	 |

In [107]:
print(' Census | {} | {} | {} | {} | {} | {} |'.format(census[6],census[7],census[8],census[9],census[10],census[11]))
for A in start:
    C=[]
    for P in census:
        C+=[NZPopCorr(A,P)]   
    print('%8s| %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t |'% (A,C[6],C[7],C[8],C[9],C[10],C[11]))    
    #print(A, C)

 Census | taxi_W_total | taxi_W_male | taxi_W_female | taxi_W_age_under_29 | taxi_W_age_30_54 | taxi_W_age_55_over |
startCount_0| 0.0900	 | 0.0830	 | 0.0956	 | 0.1596	 | 0.0771	 | 0.0475	 |
startCount_1| 0.0859	 | 0.0785	 | 0.0920	 | 0.1554	 | 0.0723	 | 0.0458	 |
startCount_2| 0.0584	 | 0.0510	 | 0.0651	 | 0.1178	 | 0.0469	 | 0.0250	 |
startCount_3| 0.0118	 | 0.0097	 | 0.0139	 | 0.0624	 | 0.0030	 | -0.0172	 |
startCount_4| 0.0387	 | 0.0403	 | 0.0363	 | 0.0788	 | 0.0317	 | 0.0143	 |
startCount_5| 0.1259	 | 0.1221	 | 0.1275	 | 0.1646	 | 0.1154	 | 0.1078	 |
startCount_6| 0.1475	 | 0.1448	 | 0.1478	 | 0.1909	 | 0.1390	 | 0.1175	 |
startCount_7| 0.1616	 | 0.1602	 | 0.1602	 | 0.2137	 | 0.1545	 | 0.1170	 |
startCount_8| 0.1888	 | 0.1833	 | 0.1911	 | 0.2473	 | 0.1797	 | 0.1415	 |
startCount_9| 0.2906	 | 0.2809	 | 0.2956	 | 0.3698	 | 0.2753	 | 0.2333	 |
startCount_10| 0.2765	 | 0.2683	 | 0.2801	 | 0.3591	 | 0.2628	 | 0.2116	 |
startCount_11| 0.2977	 | 0.2917	 | 0.2988	 | 0.3782	 | 0.2855	 | 0.2298	 |
startCount_12| 0.3355	 | 0.3303	 | 0.3349	 | 0.4163	 | 0.3235	 | 0.2644	 |
startCount_13| 0.3279	 | 0.3237	 | 0.3266	 | 0.4108	 | 0.3156	 | 0.2560	 |
startCount_14| 0.3143	 | 0.3102	 | 0.3130	 | 0.3963	 | 0.3027	 | 0.2416	 |
startCount_15| 0.3189	 | 0.3162	 | 0.3159	 | 0.3987	 | 0.3080	 | 0.2462	 |
startCount_16| 0.4274	 | 0.4281	 | 0.4191	 | 0.5049	 | 0.4177	 | 0.3475	 |
startCount_17| 0.4953	 | 0.4938	 | 0.4880	 | 0.5688	 | 0.4848	 | 0.4183	 |
startCount_18| 0.3686	 | 0.3619	 | 0.3690	 | 0.4451	 | 0.3551	 | 0.3044	 |
startCount_19| 0.2640	 | 0.2566	 | 0.2670	 | 0.3430	 | 0.2502	 | 0.2040	 |
startCount_20| 0.1991	 | 0.1931	 | 0.2018	 | 0.2752	 | 0.1862	 | 0.1435	 |
startCount_21| 0.1620	 | 0.1558	 | 0.1655	 | 0.2365	 | 0.1487	 | 0.1113	 |
startCount_22| 0.1357	 | 0.1303	 | 0.1389	 | 0.2076	 | 0.1226	 | 0.0887	 |
startCount_23| 0.1154	 | 0.1077	 | 0.1214	 | 0.1857	 | 0.1023	 | 0.0717	 |

In [108]:
print(' Census | {} | {} | {} | {} | {} | {} |'.format(census[0],census[1],census[2],census[3],census[4],census[5]))
for A in end:
    C=[]
    for P in census:
        C+=[NZPopCorr(A,P)]   
    print('%8s| %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t |'% (A,C[0],C[1],C[2],C[3],C[4],C[5]))    
    #print(A, C)

 Census | taxi_R_total | taxi_R_male | taxi_R_female | taxi_R_age_under_29 | taxi_R_age_30_54 | taxi_R_age_55_over |
endCount_0| -0.0976	 | -0.0697	 | -0.1221	 | -0.0124	 | -0.1522	 | -0.0498	 |
endCount_1| -0.0920	 | -0.0661	 | -0.1146	 | -0.0039	 | -0.1474	 | -0.0473	 |
endCount_2| -0.0807	 | -0.0544	 | -0.1039	 | 0.0142	 | -0.1393	 | -0.0398	 |
endCount_3| -0.0802	 | -0.0545	 | -0.1027	 | -0.0052	 | -0.1309	 | -0.0309	 |
endCount_4| -0.2006	 | -0.1736	 | -0.2232	 | -0.1422	 | -0.2362	 | -0.1489	 |
endCount_5| -0.2738	 | -0.2595	 | -0.2843	 | -0.2327	 | -0.2914	 | -0.2349	 |
endCount_6| -0.3171	 | -0.3065	 | -0.3238	 | -0.2702	 | -0.3377	 | -0.2719	 |
endCount_7| -0.3823	 | -0.3729	 | -0.3874	 | -0.3226	 | -0.4066	 | -0.3352	 |
endCount_8| -0.4330	 | -0.4236	 | -0.4377	 | -0.3631	 | -0.4574	 | -0.3932	 |
endCount_9| -0.4370	 | -0.4233	 | -0.4456	 | -0.3719	 | -0.4602	 | -0.3925	 |
endCount_10| -0.3997	 | -0.3787	 | -0.4151	 | -0.3473	 | -0.4258	 | -0.3309	 |
endCount_11| -0.3730	 | -0.3507	 | -0.3899	 | -0.3235	 | -0.4009	 | -0.2985	 |
endCount_12| -0.3709	 | -0.3471	 | -0.3893	 | -0.3214	 | -0.4000	 | -0.2938	 |
endCount_13| -0.3704	 | -0.3460	 | -0.3894	 | -0.3202	 | -0.4001	 | -0.2924	 |
endCount_14| -0.3634	 | -0.3389	 | -0.3823	 | -0.3173	 | -0.3916	 | -0.2839	 |
endCount_15| -0.3397	 | -0.3153	 | -0.3588	 | -0.2940	 | -0.3695	 | -0.2590	 |
endCount_16| -0.3087	 | -0.2842	 | -0.3282	 | -0.2642	 | -0.3393	 | -0.2291	 |
endCount_17| -0.2634	 | -0.2389	 | -0.2834	 | -0.2150	 | -0.2992	 | -0.1826	 |
endCount_18| -0.2375	 | -0.2119	 | -0.2587	 | -0.1865	 | -0.2761	 | -0.1571	 |
endCount_19| -0.2082	 | -0.1801	 | -0.2319	 | -0.1537	 | -0.2476	 | -0.1363	 |
endCount_20| -0.1801	 | -0.1521	 | -0.2040	 | -0.1213	 | -0.2217	 | -0.1137	 |
endCount_21| -0.1460	 | -0.1175	 | -0.1707	 | -0.0839	 | -0.1917	 | -0.0786	 |
endCount_22| -0.1105	 | -0.0805	 | -0.1368	 | -0.0444	 | -0.1599	 | -0.0443	 |
endCount_23| -0.1131	 | -0.0851	 | -0.1375	 | -0.0389	 | -0.1650	 | -0.0519	 |

In [109]:
print(' Census | {} | {} | {} | {} | {} | {} |'.format(census[6],census[7],census[8],census[9],census[10],census[11]))
for A in end:
    C=[]
    for P in census:
        C+=[NZPopCorr(A,P)]   
    print('%8s| %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t | %.4f\t |'% (A,C[6],C[7],C[8],C[9],C[10],C[11]))    
    #print(A, C)

 Census | taxi_W_total | taxi_W_male | taxi_W_female | taxi_W_age_under_29 | taxi_W_age_30_54 | taxi_W_age_55_over |
endCount_0| 0.0283	 | 0.0178	 | 0.0388	 | 0.0852	 | 0.0180	 | -0.0045	 |
endCount_1| 0.0283	 | 0.0168	 | 0.0398	 | 0.0830	 | 0.0182	 | -0.0028	 |
endCount_2| 0.0233	 | 0.0158	 | 0.0306	 | 0.0744	 | 0.0153	 | -0.0099	 |
endCount_3| 0.0004	 | -0.0049	 | 0.0060	 | 0.0477	 | -0.0066	 | -0.0298	 |
endCount_4| 0.2214	 | 0.2140	 | 0.2252	 | 0.2453	 | 0.2170	 | 0.1955	 |
endCount_5| 0.4274	 | 0.4270	 | 0.4202	 | 0.4780	 | 0.4214	 | 0.3654	 |
endCount_6| 0.4712	 | 0.4798	 | 0.4538	 | 0.5172	 | 0.4695	 | 0.3994	 |
endCount_7| 0.5196	 | 0.5306	 | 0.4989	 | 0.5731	 | 0.5172	 | 0.4389	 |
endCount_8| 0.5575	 | 0.5584	 | 0.5466	 | 0.6182	 | 0.5499	 | 0.4822	 |
endCount_9| 0.5193	 | 0.5120	 | 0.5176	 | 0.5930	 | 0.5060	 | 0.4488	 |
endCount_10| 0.3921	 | 0.3838	 | 0.3937	 | 0.4750	 | 0.3772	 | 0.3238	 |
endCount_11| 0.3077	 | 0.3020	 | 0.3082	 | 0.3927	 | 0.2939	 | 0.2389	 |
endCount_12| 0.2998	 | 0.2960	 | 0.2985	 | 0.3827	 | 0.2871	 | 0.2307	 |
endCount_13| 0.2965	 | 0.2914	 | 0.2964	 | 0.3782	 | 0.2838	 | 0.2285	 |
endCount_14| 0.2721	 | 0.2679	 | 0.2715	 | 0.3489	 | 0.2599	 | 0.2092	 |
endCount_15| 0.2449	 | 0.2391	 | 0.2467	 | 0.3211	 | 0.2324	 | 0.1857	 |
endCount_16| 0.2493	 | 0.2441	 | 0.2503	 | 0.3227	 | 0.2365	 | 0.1936	 |
endCount_17| 0.2345	 | 0.2284	 | 0.2368	 | 0.3096	 | 0.2209	 | 0.1802	 |
endCount_18| 0.1718	 | 0.1652	 | 0.1755	 | 0.2499	 | 0.1582	 | 0.1175	 |
endCount_19| 0.1088	 | 0.1019	 | 0.1141	 | 0.1826	 | 0.0968	 | 0.0581	 |
endCount_20| 0.0645	 | 0.0568	 | 0.0713	 | 0.1321	 | 0.0536	 | 0.0197	 |
endCount_21| 0.0410	 | 0.0329	 | 0.0487	 | 0.1017	 | 0.0309	 | 0.0026	 |
endCount_22| 0.0352	 | 0.0261	 | 0.0442	 | 0.0938	 | 0.0255	 | -0.0014	 |
endCount_23| 0.0292	 | 0.0195	 | 0.0387	 | 0.0865	 | 0.0192	 | -0.0048	 |